#pragma GCC diagnostic ignored "-Wunknown-pragmas"

#pragma region HEAD

/* 
 * If you compile and run this you should see a
 * grey initialized Window.
 * 
 * SDL_FillRect
 * SDL_MapRGB
 * 
 */

/* DEFINED PROGRESS GOALS
 * 
 * Fill Window
 * 
 */

#include <stdlib.h>
#include <SDL2/SDL.h>

SDL_Window   *Window;
SDL_Surface  *screen;

#pragma endregion 	HEAD

#pragma region MAIN
int main(int argc, char *argv[])
{

(void)argc;
(void)argv;

SDL_Init(SDL_INIT_VIDEO);

// create window with one call
Window = SDL_CreateWindow("Fill Window",SDL_WINDOWPOS_CENTERED,SDL_WINDOWPOS_CENTERED, 200, 200, 0);

// Defining the pointer and let it point to the Window's surface.
screen = SDL_GetWindowSurface(Window);

/* The SDL_MapRGB() function
 * 
 * maps the RGB color value to the specified pixel format and returns the pixel
 * value best approximating the given RGB color value for the given pixel
 * format.
 * 
 * Returns a pixel value
 * 
 */

// This function call is maps the RGB value to the right pixel format
Uint32 color = SDL_MapRGB(screen->format, 113, 113, 113);

// This function gives every pixel on the surface the same color
// Filling the the Surface's rect.
SDL_FillRect(screen, NULL, color);
// https://wiki.libsdl.org/SDL_FillRect
/*
 *  Performs a fast fill of the given rectangle with color.
 *
 *  If rect is NULL, the whole surface will be filled with color.
 *
 *  The color should be a pixel of the format used by the surface, and
 *  can be generated by the SDL_MapRGB() function.
 *  Gonna look later into this.
 * 
 *  return 0 on success, or -1 on error.
 */

SDL_Event event;

int running=1;

// https://wiki.libsdl.org/SDL_UpdateWindowSurface
// Use this function to copy the window surface to the screen.
SDL_UpdateWindowSurface(Window);
/* Declared in SDL_video.h
 * I called it before the main loop because, there is no update.
 */

while(running){
	while(SDL_PollEvent(&event)){
		if(event.type == SDL_QUIT){
			running=0;
		}
	}
	SDL_Delay(16);
}
// Freeing the surface is necessary!
SDL_FreeSurface(screen);
SDL_DestroyWindow(Window);
SDL_Quit();

return EXIT_SUCCESS;

}
#pragma endregion   MAIN

