//BEGIN HEAD
//BEGIN DESCRIPTION

/* 
 * If you compile and run this you should see an
 * black initialized Window with icon.
 * 
 */

/* DEFINED PROGRESS GOALS
 * 
 * TODO Inititalize Window
 * TODO Set Icon
 * 
 */
//END   DESCRIPTION

//BEGIN INCLUDES
#include <stdlib.h>
#include <SDL2/SDL.h>
//END   INCLUDES

//BEGIN CPP DEFINITIONS
//END   CPP DEFINITIONS

//BEGIN DATASTRUCTURES
//END	DATASTRUCTURES

//BEGIN GLOBALS
SDL_Window   *Window;
/* Declare a a pointer to struct surface which holds a bitmap
 * and Metadata, the struct is declared in SDL_surface.h
 */
SDL_Surface  *screen;
//BEGIN VISIBLES
//END 	VISIBLES

//END   GLOBALS

//BEGIN FUNCTION PROTOTYPES
//END	FUNCTION PROTOTYPES

//END 	HEAD

//BEGIN MAIN FUNCTION
int main(int argc, char *argv[])
{
(void)argc;
(void)argv;

//BEGIN INIT
SDL_Init(SDL_INIT_VIDEO);
//BEGIN WINDOW
Window = SDL_CreateWindow("", 0, 0, 0, 0, SDL_WINDOW_HIDDEN);
SDL_SetWindowPosition(Window,0,0);
SDL_SetWindowSize(Window,800/2,600/2);
SDL_SetWindowTitle(Window, "SDL2 Second Window");
SDL_ShowWindow(Window);

//BEGIN ICON
//TODO Description
SDL_Surface *icon;
icon=SDL_LoadBMP("./assets/gfx/SDL2.bmp");
SDL_SetWindowIcon(Window, icon);
SDL_FreeSurface(icon);
//END 	ICON

//Defining the pointer and let it point to the Window's surface.
screen = SDL_GetWindowSurface(Window);
//Filling the the Surface's rect.
SDL_FillRect(screen, NULL, 0);
//https://wiki.libsdl.org/SDL_FillRect
/*
 *  Performs a fast fill of the given rectangle with color.
 *
 *  If rect is NULL, the whole surface will be filled with color.
 *
 *  The color should be a pixel of the format used by the surface, and
 *  can be generated by the SDL_MapRGB() function.
 *  Gonna look later into this.
 * 
 *  return 0 on success, or -1 on error.
 */
//END WINDOW

SDL_Event event;

int running=1;
//https://wiki.libsdl.org/SDL_UpdateWindowSurface
//Use this function to copy the window surface to the screen.
SDL_UpdateWindowSurface(Window);
/* Declared in SDL_video.h
 * I called it before the main loop because, there is no update.
 */

//END   INIT
//BEGIN MAIN LOOP
while(running){
	//BEGIN EVENT LOOP
	while(SDL_PollEvent(&event)){
		if(event.type == SDL_QUIT){
			running=0;
		}
	}
	//END   EVENT LOOP
	SDL_Delay(16);
	//BEGIN RENDERING
	//END   RENDERING
}
//END   MAIN LOOP
//Freeing the surface is neccessary!
SDL_FreeSurface(screen);
SDL_DestroyWindow(Window);
SDL_Quit();

return EXIT_SUCCESS;

}
//END   MAIN FUNCTION

//BEGIN FUNCTIONS
//END   FUNCTIONS
